---
title: "Rainfall/Seasonal Adjustment Exploration"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(caret)
library(recipes)

knitr::opts_chunk$set(echo = FALSE)

source("./Scripts/Settings.R")
source("./Scripts/AusWeather.R")
source("./Scripts/AusClimate.R")
source("./Scripts/AusMaps.r")
source("./Scripts/AusRainfall.r")
source("./Scripts/SOI.r")
source("./Scripts/Utility.R")

```

## Load our best quality data

```{r}

# Analysis period
baseline_start <- 1950
baseline_end <- 2017
n_quantile <- 11

# Minimum number of years of data
# Allow stations to drop out for a few years
clean_years <- baseline_end - baseline_start - 2

# Load the data
rainfall_data <- aus_memorised_rainfall_data(baseline_start, baseline_end, clean_years)
stations <- rainfall_data$stations
observations <- rainfall_data$observations
monthly_observations <- aus_rainfall_monthly_observations(observations)
baselines <- aus_rainfall_baselines(monthly_observations, baseline_start, baseline_end, n_quantile)
monthly_valuations <- aus_rainfall_monthly_valuations(monthly_observations, baselines, n_quantile)
regions <- aus_rainfall_regions(stations, monthly_valuations, 2000, 10, 12, 3, 7)

soi_df <- soi_load() %>% mutate(SOI.Standard = scale(SOI))

```

## Trend plot

```{r}

trend_plot <- function(regionID, start_period, end_period) {
    
    df <- 
        monthly_valuations %>%
        inner_join(regions, by = c("Zone", "Station")) %>% 
        filter(RegionID %in% regionID) %>%
        filter(Major_Period >= start_period, Major_Period <= end_period)
    df_summary <- 
        df %>%
        group_by(Date) %>%
        summarise(Rainfall.L12.Median = median(Rainfall.L12))

    trend_plot <-
        df_summary %>%
        ggplot(aes(x = Date, y = Rainfall.L12.Median)) +
        geom_line(color = "grey30") +
        geom_smooth(formula = y ~ x, method = "lm", color = "blue") +
        labs(
            x = "Date",
            y = "Monthly median rainfall (mm)"
        ) +
        theme_bw()
    trend_plot
}

```

## Vic

```{r}

regionID <- 3
start_period <- 2000
end_period <- baseline_end

region_monthly_rain <- 
    monthly_valuations %>%
        inner_join(regions, by = c("Zone", "Station")) %>% 
        filter(RegionID %in% regionID) %>%
        filter(Major_Period >= start_period, Major_Period <= end_period) %>%
        group_by(Date) %>%
        summarise(Rainfall = median(Rainfall), Rainfall.Rating = mean(Rainfall.Rating)) %>%
        mutate(Rainfall.Standard = scale(Rainfall), Rainfall.Rating.Standard = scale(Rainfall.Rating))

region_monthly_soi <-
    soi_df %>%
    filter(Year >= start_period, Year <= end_period)

region_monthly_rain %>%
    ggplot(aes(x = Date, y = Rainfall.Rating.Standard)) +
    geom_line(aes(color = "Rainfall")) +
    geom_line(data = region_monthly_soi, aes(y = SOI.Standard, color = "SOI"), alpha = 0.6) +
    labs(
        x = "Date",
        y = "Values"
    ) +
    theme_bw()

```

** Rain Month **

```{r, fig.asp = 1}

region_monthly_rain %>%
    ggplot(aes(x = month(Date), y = Rainfall)) +
    geom_point()

```

** Rating vs SOI scatter **

```{r, fig.asp = 1}

region_monthly_rain %>%
    inner_join(region_monthly_soi, by = c("Date")) %>%
    crossing(Lag = 0) %>%
    group_by(Lag) %>%
    arrange(Date) %>%
    mutate(SOI_Lag = lag(SOI, first(Lag))) %>%
    ungroup() %>%
    ggplot(aes(x = Rainfall.Rating, y = SOI_Lag)) +
    geom_point() +
    facet_wrap(~ Lag)

```

** Predict Median **

```{r}

emc_algorithms() %>% filter(core, regression)

```

```{r, fig.asp = 1}

algorithms <- c("earth", "glmnet", "lm", "M5", "null", "pls", "rpart", "svmLinear", "svmPoly", "svmRadial", "rf")
tr_parameters <- expand.grid(algorithm = algorithms) %>% mutate(label = paste0("Algorithm ", algorithm))

regionID <- 3
start_period <- baseline_start
end_period <- baseline_end

tr_df <- 
    monthly_valuations %>%
        inner_join(regions, by = c("Zone", "Station")) %>% 
        filter(RegionID %in% regionID) %>%
        filter(Major_Period >= start_period, Major_Period <= end_period) %>%
        group_by(Date) %>%
        summarise(Rainfall = median(Rainfall), Rainfall.Rating = mean(Rainfall.Rating)) %>%
        mutate(Month = month(Date))
tr_recipe <-
    recipe(Rainfall ~ Month, tr_df)

tr_control <- trainControl(method = "boot")
metric <- "RMSE"
seed <- 100
tr_emc <-
    emc_bind(
        tr_parameters,
        emc_record(
            train = {
                set.seed(seed)
                train(tr_recipe, tr_df, method = algorithm, trControl = tr_control) 
            }
            ,
            .label = label,
            .verbose = FALSE
        )
    )
tr_emc %>% select(algorithm, train_error, train_warnings)
tr_working_emc <- tr_emc %>% filter(train_errors == 0) %>% emc_bind(emc_resamples(train))
```

** Resamples **

```{r}
tr_resamples <- tr_working_emc %>% unnest(resamples) %>% select(algorithm, RMSE, MAE, Resample)
ggplot(tr_resamples) + geom_boxplot(aes(x = algorithm, y = RMSE))

```

** Predictions **

**Calc**

```{r}

emc_augment <- function(.train, .data, .variable) {
    
    variable_name <- quo_name(.variable)
    prediction_var <- sym(sprintf("%s.Prediction", variable_name))
    residual_var <- sym(sprintf("%s.Residual", variable_name))
    train <- .train[[1]]
    if (is.null(train)) {
        return(tibble::tibble()[1,])
    }
    prediction <- predict(train, newdata = .data)
    original <- tr_df %>% pull(!! .variable)
    residual <- original - prediction
    augment_df <- bind_cols(!! prediction_var := prediction, !! residual_var := residual, .data)
    tibble(augment = list(augment_df))
}

tr_augment_emc <- 
    emc_bind(
        tr_working_emc,
        emc_augment(train, tr_df, quo(Rainfall))
    )
tr_augmented <- tr_augment_emc %>% select(algorithm, augment) %>% unnest(augment)
tr_augmented

```

** Rain Month **

```{r, fig.asp = 1}

tr_augmented %>%
    ggplot(aes(x = Month)) +
    geom_jitter(aes(y = Rainfall, color = "Original"), alpha = .7, width = 0.25, size = 1) +
    geom_point(aes(y = Rainfall.Prediction)) +
    facet_wrap(~ algorithm)

```

** Rain residual **

```{r, fig.asp = 1}

tr_augmented %>%
    ggplot(aes(x = Month)) +
    geom_jitter(aes(y = Rainfall.Residual), alpha = .7, width = 0.25, size = 1) +
    facet_wrap(~ algorithm)

```


svmRadial captures the shape the best.

## SOI versus Seasonally corrected

```{r}

season_adjusted_rainfall <- 
    tr_augmented %>% 
    filter(algorithm == "svmRadial") %>% 
    select(-algorithm) %>% 
    as_tibble() %>%
    mutate(Rainfall.Seasonal = Rainfall.Residual + median(Rainfall)) %>%
    inner_join(soi_df, by = "Date") %>%
    mutate(Rainfall.Standard = scale(Rainfall)) %>%
    mutate(Rainfall.Seasonal.Standard = Rainfall.Residual / sd(Rainfall)) %>%
    select(
        Year, Month = Month.x, Date, 
        Rainfall, Rainfall.Standard, Rainfall.Rating, Rainfall.Seasonal, Rainfall.Seasonal.Standard, 
        SOI, SOI.Standard)

season_adjusted_rainfall %>%
    filter(Year >= 1970, Year <= 1980) %>%
    ggplot(aes(x = Date)) +
    geom_line(aes(y = Rainfall.Standard, color = "Rainfall")) +
    geom_line(aes(y = Rainfall.Seasonal.Standard, color = "Seasonal Rainfall"), alpha = 0.6) +
    geom_line(aes(y = SOI.Standard, color = "SOI"), alpha = 0.6) +
    labs(
        x = "Date",
        y = "Values"
    ) +
    theme_bw()


```

## SOI versus Rainfall

```{r}

season_adjusted_rainfall %>%
    ggplot(aes(y = Rainfall.Seasonal, x = SOI)) +
    geom_point()
```


