install.packages("tidyverse")
install.packages("caret")
# install.packages("lazyeval")
install.packages("doParallel")
install.packages("doSNOW")
# install.packages("memoise")
install.packages("e1071")
install.packages("lubridate")
install.packages("AppliedPredictiveModeling")
install.packages("RANN")
# install.packages("evaluate")
